spring:
  application:
    name: login-mfa

  # Virtual Threads (Java 21)
  threads:
    virtual:
      enabled: true

  # PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/loginmfa
    username: app
    password: app
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5

  # JPA
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  # Flyway
  flyway:
    enabled: true
    locations: classpath:db/migration

  # Redis
  data:
    redis:
      host: localhost
      port: 6379

  # Email (Mailhog)
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:minha-chave-secreta-para-desenvolvimento-local-apenas-trocar-em-producao}
  access-token:
    expiration: 900000      # 15 minutos em ms
  refresh-token:
    expiration: 604800000   # 7 dias em ms
  mfa-token:
    expiration: 300000      # 5 minutos em ms

# MFA Configuration
mfa:
  code:
    length: 6
    ttl: 300                # 5 minutos em segundos
  block:
    max-attempts: 3
    ttl: 900                # 15 minutos em segundos

# Server
server:
  port: 8080

# Logging
logging:
  level:
    br.com.labs: DEBUG
    org.springframework.security: DEBUG
